# Form implementation generated from reading ui file 'batch_status.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_batch_status(object):
    def setupUi(self, batch_status):
        batch_status.setObjectName("batch_status")
        batch_status.resize(291, 199)
        batch_status.setStyleSheet("* {\n"
"    font-family: \'DejaVu Sans\';\n"
"}\n"
"\n"
"QProgressBar {\n"
"    border: 1px solid #bbb;\n"
"    border-radius: 4px;\n"
"    text-align: center;\n"
"    background: #444444;\n"
"    color: white;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #228B22;\n"
"    width: 6px;      \n"
"    margin: 1px;  \n"
"}")
        self.progressBar_alignment = QtWidgets.QProgressBar(parent=batch_status)
        self.progressBar_alignment.setGeometry(QtCore.QRect(10, 110, 271, 25))
        self.progressBar_alignment.setStyleSheet("font-weight: bold;\n"
"font-size: 11pt;")
        self.progressBar_alignment.setProperty("value", 0)
        self.progressBar_alignment.setObjectName("progressBar_alignment")
        self.label_processing = QtWidgets.QLabel(parent=batch_status)
        self.label_processing.setGeometry(QtCore.QRect(10, 8, 201, 20))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_processing.setFont(font)
        self.label_processing.setStyleSheet("font-size: 10pt;")
        self.label_processing.setObjectName("label_processing")
        self.pushButton = QtWidgets.QPushButton(parent=batch_status)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(220, 8, 61, 21))
        self.pushButton.setStyleSheet("background-color: #8B0000;\n"
"font-weight: bold;\n"
"color: white;\n"
"font-size: 10.5pt;")
        self.pushButton.setObjectName("pushButton")
        self.label_alignment_status = QtWidgets.QLabel(parent=batch_status)
        self.label_alignment_status.setGeometry(QtCore.QRect(10, 90, 161, 21))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_alignment_status.setFont(font)
        self.label_alignment_status.setStyleSheet("font-size: 10pt;")
        self.label_alignment_status.setObjectName("label_alignment_status")
        self.progressBar_quantitation = QtWidgets.QProgressBar(parent=batch_status)
        self.progressBar_quantitation.setGeometry(QtCore.QRect(10, 160, 271, 25))
        self.progressBar_quantitation.setStyleSheet("font-weight: bold;\n"
"font-size: 11pt;")
        self.progressBar_quantitation.setProperty("value", 0)
        self.progressBar_quantitation.setObjectName("progressBar_quantitation")
        self.label_quantitation_status = QtWidgets.QLabel(parent=batch_status)
        self.label_quantitation_status.setGeometry(QtCore.QRect(10, 140, 161, 21))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_quantitation_status.setFont(font)
        self.label_quantitation_status.setStyleSheet("font-size: 10pt;")
        self.label_quantitation_status.setObjectName("label_quantitation_status")
        self.label_alignment_status_2 = QtWidgets.QLabel(parent=batch_status)
        self.label_alignment_status_2.setGeometry(QtCore.QRect(10, 40, 271, 21))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_alignment_status_2.setFont(font)
        self.label_alignment_status_2.setStyleSheet("font-size: 10pt;")
        self.label_alignment_status_2.setObjectName("label_alignment_status_2")
        self.progressBar_analytes_ref = QtWidgets.QProgressBar(parent=batch_status)
        self.progressBar_analytes_ref.setGeometry(QtCore.QRect(10, 60, 271, 25))
        self.progressBar_analytes_ref.setStyleSheet("font-weight: bold;\n"
"font-size: 11pt;")
        self.progressBar_analytes_ref.setProperty("value", 0)
        self.progressBar_analytes_ref.setObjectName("progressBar_analytes_ref")

        self.retranslateUi(batch_status)
        QtCore.QMetaObject.connectSlotsByName(batch_status)

    def retranslateUi(self, batch_status):
        _translate = QtCore.QCoreApplication.translate
        batch_status.setWindowTitle(_translate("batch_status", "Batch process"))
        self.progressBar_alignment.setFormat(_translate("batch_status", "Not performed"))
        self.label_processing.setText(_translate("batch_status", "Status..."))
        self.pushButton.setText(_translate("batch_status", "Abort"))
        self.label_alignment_status.setText(_translate("batch_status", "Alignment status:"))
        self.progressBar_quantitation.setFormat(_translate("batch_status", "Not performed"))
        self.label_quantitation_status.setText(_translate("batch_status", "Quantitation status:"))
        self.label_alignment_status_2.setText(_translate("batch_status", "Generation of analytes reference file:"))
        self.progressBar_analytes_ref.setFormat(_translate("batch_status", "Not performed"))
