# Form implementation generated from reading ui file 'gui_advanced_settings.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_advanced_settings(object):
    def setupUi(self, advanced_settings):
        advanced_settings.setObjectName("advanced_settings")
        advanced_settings.resize(389, 180)
        advanced_settings.setStyleSheet("* {\n"
"    font-family: \'DejaVu Sans\';\n"
"    font-size: 10pt; \n"
"}\n"
"\n"
"#frame {\n"
"    border: 1px solid #b0b0b0;\n"
"}")
        self.frame = QtWidgets.QFrame(parent=advanced_settings)
        self.frame.setGeometry(QtCore.QRect(10, 10, 371, 161))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.doubleSpinBox_constant = QtWidgets.QDoubleSpinBox(parent=self.frame)
        self.doubleSpinBox_constant.setGeometry(QtCore.QRect(130, 130, 151, 22))
        self.doubleSpinBox_constant.setDecimals(10)
        self.doubleSpinBox_constant.setSingleStep(1e-06)
        self.doubleSpinBox_constant.setObjectName("doubleSpinBox_constant")
        self.checkBox_quadratic = QtWidgets.QCheckBox(parent=self.frame)
        self.checkBox_quadratic.setGeometry(QtCore.QRect(10, 10, 441, 21))
        self.checkBox_quadratic.setObjectName("checkBox_quadratic")
        self.label_mz2_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_mz2_2.setGeometry(QtCore.QRect(290, 90, 71, 21))
        self.label_mz2_2.setObjectName("label_mz2_2")
        self.label_mz2 = QtWidgets.QLabel(parent=self.frame)
        self.label_mz2.setGeometry(QtCore.QRect(290, 50, 71, 21))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_mz2.setFont(font)
        self.label_mz2.setObjectName("label_mz2")
        self.doubleSpinBox_mz2 = QtWidgets.QDoubleSpinBox(parent=self.frame)
        self.doubleSpinBox_mz2.setGeometry(QtCore.QRect(130, 50, 151, 22))
        self.doubleSpinBox_mz2.setDecimals(10)
        self.doubleSpinBox_mz2.setSingleStep(1e-06)
        self.doubleSpinBox_mz2.setObjectName("doubleSpinBox_mz2")
        self.doubleSpinBox_mz = QtWidgets.QDoubleSpinBox(parent=self.frame)
        self.doubleSpinBox_mz.setGeometry(QtCore.QRect(130, 90, 151, 22))
        self.doubleSpinBox_mz.setDecimals(10)
        self.doubleSpinBox_mz.setSingleStep(1e-06)
        self.doubleSpinBox_mz.setObjectName("doubleSpinBox_mz")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(20, 50, 111, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(110, 90, 21, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(110, 130, 21, 21))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(advanced_settings)
        QtCore.QMetaObject.connectSlotsByName(advanced_settings)

    def retranslateUi(self, advanced_settings):
        _translate = QtCore.QCoreApplication.translate
        advanced_settings.setWindowTitle(_translate("advanced_settings", "Advanced settings"))
        self.checkBox_quadratic.setText(_translate("advanced_settings", "Enable quadratic quantitation m/z window (experimental)"))
        self.label_mz2_2.setText(_translate("advanced_settings", "× (m/z)"))
        self.label_mz2.setText(_translate("advanced_settings", "× (m/z)²"))
        self.label.setText(_translate("advanced_settings", "m/z window = "))
        self.label_2.setText(_translate("advanced_settings", "+"))
        self.label_3.setText(_translate("advanced_settings", "+"))
