# Form implementation generated from reading ui file 'gui_advanced_settings.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_advanced_settings(object):
    def setupUi(self, advanced_settings):
        advanced_settings.setObjectName("advanced_settings")
        advanced_settings.resize(401, 330)
        advanced_settings.setStyleSheet("* {\n"
"    font-family: \'DejaVu Sans\';\n"
"    font-size: 10pt; \n"
"}\n"
"\n"
"#frame {\n"
"    border: 1px solid #b0b0b0;\n"
"}\n"
"\n"
"#frame_2 {\n"
"    border: 1px solid #b0b0b0;\n"
"}\n"
"\n"
"#frame_3 {\n"
"    border: 1px solid #b0b0b0;\n"
"}")
        self.frame = QtWidgets.QFrame(parent=advanced_settings)
        self.frame.setGeometry(QtCore.QRect(10, 20, 381, 161))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.mz2_exponent = QtWidgets.QDoubleSpinBox(parent=self.frame)
        self.mz2_exponent.setGeometry(QtCore.QRect(245, 38, 43, 22))
        self.mz2_exponent.setDecimals(0)
        self.mz2_exponent.setMinimum(-64.0)
        self.mz2_exponent.setMaximum(64.0)
        self.mz2_exponent.setSingleStep(1.0)
        self.mz2_exponent.setObjectName("mz2_exponent")
        self.checkBox_quadratic = QtWidgets.QCheckBox(parent=self.frame)
        self.checkBox_quadratic.setGeometry(QtCore.QRect(10, 10, 441, 21))
        self.checkBox_quadratic.setObjectName("checkBox_quadratic")
        self.label_mz2 = QtWidgets.QLabel(parent=self.frame)
        self.label_mz2.setGeometry(QtCore.QRect(300, 50, 41, 21))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_mz2.setFont(font)
        self.label_mz2.setObjectName("label_mz2")
        self.mz2_coeff = QtWidgets.QDoubleSpinBox(parent=self.frame)
        self.mz2_coeff.setGeometry(QtCore.QRect(120, 50, 81, 22))
        self.mz2_coeff.setDecimals(5)
        self.mz2_coeff.setMinimum(-9.99999)
        self.mz2_coeff.setMaximum(9.99999)
        self.mz2_coeff.setSingleStep(0.01)
        self.mz2_coeff.setObjectName("mz2_coeff")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(20, 52, 101, 16))
        self.label.setObjectName("label")
        self.label_10_a = QtWidgets.QLabel(parent=self.frame)
        self.label_10_a.setGeometry(QtCore.QRect(210, 50, 31, 21))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_10_a.setFont(font)
        self.label_10_a.setObjectName("label_10_a")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(100, 92, 16, 16))
        self.label_2.setObjectName("label_2")
        self.mz_coeff = QtWidgets.QDoubleSpinBox(parent=self.frame)
        self.mz_coeff.setGeometry(QtCore.QRect(120, 90, 81, 22))
        self.mz_coeff.setDecimals(5)
        self.mz_coeff.setMinimum(-9.99999)
        self.mz_coeff.setMaximum(9.99999)
        self.mz_coeff.setSingleStep(0.01)
        self.mz_coeff.setObjectName("mz_coeff")
        self.label_10_b = QtWidgets.QLabel(parent=self.frame)
        self.label_10_b.setGeometry(QtCore.QRect(210, 90, 31, 21))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_10_b.setFont(font)
        self.label_10_b.setObjectName("label_10_b")
        self.label_mz = QtWidgets.QLabel(parent=self.frame)
        self.label_mz.setGeometry(QtCore.QRect(300, 90, 41, 21))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_mz.setFont(font)
        self.label_mz.setObjectName("label_mz")
        self.mz_exponent = QtWidgets.QDoubleSpinBox(parent=self.frame)
        self.mz_exponent.setGeometry(QtCore.QRect(245, 78, 43, 22))
        self.mz_exponent.setDecimals(0)
        self.mz_exponent.setMinimum(-64.0)
        self.mz_exponent.setMaximum(64.0)
        self.mz_exponent.setSingleStep(1.0)
        self.mz_exponent.setObjectName("mz_exponent")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(100, 130, 16, 16))
        self.label_3.setObjectName("label_3")
        self.constant_exponent = QtWidgets.QDoubleSpinBox(parent=self.frame)
        self.constant_exponent.setGeometry(QtCore.QRect(245, 118, 43, 22))
        self.constant_exponent.setDecimals(0)
        self.constant_exponent.setMinimum(-64.0)
        self.constant_exponent.setMaximum(64.0)
        self.constant_exponent.setSingleStep(1.0)
        self.constant_exponent.setObjectName("constant_exponent")
        self.label_10_c = QtWidgets.QLabel(parent=self.frame)
        self.label_10_c.setGeometry(QtCore.QRect(210, 130, 31, 21))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_10_c.setFont(font)
        self.label_10_c.setObjectName("label_10_c")
        self.constant_coeff = QtWidgets.QDoubleSpinBox(parent=self.frame)
        self.constant_coeff.setGeometry(QtCore.QRect(120, 130, 81, 22))
        self.constant_coeff.setDecimals(5)
        self.constant_coeff.setMinimum(-9.99999)
        self.constant_coeff.setMaximum(9.99999)
        self.constant_coeff.setSingleStep(0.01)
        self.constant_coeff.setObjectName("constant_coeff")
        self.frame_2 = QtWidgets.QFrame(parent=advanced_settings)
        self.frame_2.setGeometry(QtCore.QRect(10, 190, 381, 41))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.checkBox_peakHeights = QtWidgets.QCheckBox(parent=self.frame_2)
        self.checkBox_peakHeights.setGeometry(QtCore.QRect(10, 10, 351, 21))
        self.checkBox_peakHeights.setObjectName("checkBox_peakHeights")
        self.frame_3 = QtWidgets.QFrame(parent=advanced_settings)
        self.frame_3.setGeometry(QtCore.QRect(10, 240, 381, 41))
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.checkBox_save_xy = QtWidgets.QCheckBox(parent=self.frame_3)
        self.checkBox_save_xy.setGeometry(QtCore.QRect(10, 10, 351, 21))
        self.checkBox_save_xy.setObjectName("checkBox_save_xy")
        self.pushButton_apply_advanced_settings = QtWidgets.QPushButton(parent=advanced_settings)
        self.pushButton_apply_advanced_settings.setGeometry(QtCore.QRect(300, 290, 91, 31))
        self.pushButton_apply_advanced_settings.setObjectName("pushButton_apply_advanced_settings")
        self.pushButton_cancel_advanced_settings = QtWidgets.QPushButton(parent=advanced_settings)
        self.pushButton_cancel_advanced_settings.setGeometry(QtCore.QRect(200, 290, 91, 31))
        self.pushButton_cancel_advanced_settings.setStyleSheet("background-color: #8B0000;\n"
"font-weight: bold;\n"
"color: white;\n"
"font-size: 10.5pt;")
        self.pushButton_cancel_advanced_settings.setObjectName("pushButton_cancel_advanced_settings")

        self.retranslateUi(advanced_settings)
        QtCore.QMetaObject.connectSlotsByName(advanced_settings)

    def retranslateUi(self, advanced_settings):
        _translate = QtCore.QCoreApplication.translate
        advanced_settings.setWindowTitle(_translate("advanced_settings", "Advanced settings"))
        self.checkBox_quadratic.setText(_translate("advanced_settings", "Use quadratic quantitation m/z window"))
        self.label_mz2.setText(_translate("advanced_settings", "(m/z)²"))
        self.label.setText(_translate("advanced_settings", "m/z window = "))
        self.label_10_a.setText(_translate("advanced_settings", "× 10"))
        self.label_2.setText(_translate("advanced_settings", "+"))
        self.label_10_b.setText(_translate("advanced_settings", "× 10"))
        self.label_mz.setText(_translate("advanced_settings", "(m/z)"))
        self.label_3.setText(_translate("advanced_settings", "+"))
        self.label_10_c.setText(_translate("advanced_settings", "× 10"))
        self.checkBox_peakHeights.setText(_translate("advanced_settings", "Report peak heights instead of areas"))
        self.checkBox_save_xy.setText(_translate("advanced_settings", "Save mass spectra in \'.xy\' format"))
        self.pushButton_apply_advanced_settings.setText(_translate("advanced_settings", "OK"))
        self.pushButton_cancel_advanced_settings.setText(_translate("advanced_settings", "Cancel"))
